### ISSUE TITLE
Web Error On Calibration Page

### ISSUE THREAD

**Issue by dxmnkd316** [ESPresense/ESPresense-companion#1664]
I'm getting an error when I click on the calibration page after updating from 2.1.2 to 2.2.1.  After the error, all other buttons and functions on the companion fail.  Only reloading or navigating to another Home Assistant page will fix it.  But returning to the calibration page kills it again.  

In the devtools it throws the error as soon as the page starts to load:

Uncaught TypeError: crypto.randomUUID is not a function
    at Zo (tooltip.ts:9:38)
    at NodeCalibrationMatrix.svelte:98:55
    at actions.js:15:31
    at ae (runtime.js:759:10)
    at actions.js:15:17
    at Ft (runtime.js:259:16)
    at q (runtime.js:468:18)
    at Ze (batch.js:1082:4)
    at #u (batch.js:379:3)
    at L.flush (batch.js:596:9)

**Comment by dxmnkd316** [comment]
Never mind.  Must have been a typo or something in the config.  I restored to 2.1.2 and my pre-upgrade config.yaml.  I then re-updated to 2.2.1 and re-typed the new parameters.  Everything is working again

**Comment by dxmnkd316** [comment]
Ok, I did a hard refresh and dumped the cache.  It's back again.  Please reopen.
